CC =gcc
CCFLAGS= -Wall -Wextra

lab1a: lab1a.o
	$(CC) -o lab1a lab1a.o
lab1a.o: lab1a.c
	$(CC) -c lab1a.c
check: 
clean: 
	rm lab1a lab1a.o lab1a-804794021.tar.gz
dist: 
	tar -czvf lab1a-804794021.tar.gz lab1a.c  Makefile 
