CC =gcc
CCFLAGS= -Wall -Wextra

default:
	$(CC) -pthread -o lab2_add lab2_add.c
	$(CC) -pthread -o lab2_list lab2_list.c SortedList.c
check: 
test:
graphs:

clean:
	rm lab2_list lab2_add lab2a-804794021.tar.gz
dist:
	tar -czvf lab2a-804794021.tar.gz README lab2_add.c lab2_list.c SortedList.c SortedList.h lab2_add.csv lab2_list.csv Makefile 