CC =gcc
CCFLAGS= -Wall -Wextra

Lab2: lab2.o
	$(CC) -o lab2 lab2.o
lab2.o: lab2.c
	$(CC) -c lab2.c
check: 
clean: 
	rm simpsh lab2.o lab2 lab2-804794021.tar.gz
dist: 
	tar -czvf lab2-804794021.tar.gz README lab12.c Makefile 
